### PR TITLE
UIU-2081: Show user-readable message when user is not found

### PR DESCRIPTION
**Pull request by mkuklis**
https://issues.folio.org/browse/UIU-2081

user-not-found

### CODE REVIEW

**Review by axelhunn — APPROVED** [review]

**Comment by axelhunn** [comment]
Great!
Will it cover the user's loan pages too?
Like https://folio-snapshot.dev.folio.org/users/df7f4993-8c14-4a0f-ab63-93975ab01c76/loans/view/cf23adf0-61ba-4887-bf82-956c4aae2260

**Review by zburke — APPROVED** [review]
👏 👏 👏

**Comment by mkuklis** [comment]
@axelhunn I don't think  https://folio-snapshot.dev.folio.org/users/df7f4993-8c14-4a0f-ab63-93975ab01c76/loans/view/cf23adf0-61ba-4887-bf82-956c4aae2260 will be covered with this work since it looks like this is a different route/container:

https://github.com/folio-org/ui-users/blob/master/src/index.js#L181

But the pattern to fix it should be similar to the work in this PR.

**Comment by mkuklis** [comment]
It looks like we have the same pattern in many places :/

https://github.com/folio-org/ui-users/search?q=getUser

I think some bigger refactoring will be required to handle this in clean way.

**Review by Baroquem — APPROVED** [review]

**Pull request merged**
