### PR TITLE
UIU-2702 create Jest/RTL test for RequestPreferencesEdit.js

### PR DESCRIPTION
**Pull request by cchitneedi**
Refs:
ui-users
Ticket: UIU-2702
URL: https://issues.folio.org/browse/UIU-2702

### CODE REVIEW

**Review by zburke — CHANGES_REQUESTED** [review]
Please remove the debugging output and clean up the lint errors.

**Comment by mkuklis** [comment]
Please cleanup lint issues. You can find them here: https://github.com/folio-org/ui-users/pull/2287/files

For example:

`'render' is defined but never used. Allowed unused vars must match /React/u`

After this should be ready to go.

**Comment by cchitneedi** [comment]
Hi @mkuklis 
Could you please suggest to write wrapper which updates the props under componentDidUpdate conditions (Line 40 - 49) from js file. Also the statement on how to cover servicePoint.pickupLocation (Line number: 233 - 238)

Thanks and Regards,
Charan

**Review by mkuklis — APPROVED** [review]
@cchitneedi I see one more little issue with eslint. After that please merge it in! 
Please make sure to use "Squash and Merge" button while merging.

**Review by zburke — APPROVED** [review]

**Pull request merged**
