### PR TITLE
UIU-2893 Use new WSAPI for adding patron/staff notes to loans

### PR DESCRIPTION
**Pull request by MikeTaylor**
Fixes UIU-2893.

No user-visible changes, just the use of a newer WSAPI.

### CODE REVIEW

**Review by zburke — COMMENTED** [review]
If this does indeed leverage a "new WSAPI" as indicated in the title, should there be version bump in the okapi interface in `package.json`? Or does this leverage functionality that was already there, and we're only now leveraging it?

**Comment by MikeTaylor** [comment]
> If this does indeed leverage a "new WSAPI" as indicated in the title, should there be version bump in the okapi interface in `package.json`? Or does this leverage functionality that was already there, and we're only now leveraging it?

See [this commit](https://github.com/folio-org/ui-users/pull/2490/commits/7cee4e1876b88b21808e31d4a5a5ece76dc28dbc).

**Review by zburke — CHANGES_REQUESTED** [review]
We are ships passing in the night 😆 

A new required okapi interface is a breaking change. Please bump the package version to 10.0.0 and then this LGTM.

**Comment by MikeTaylor** [comment]
@zburke Re-review, please!

**Review by zburke — APPROVED** [review]
LGTM

**Pull request merged**
