### PR TITLE
UIU-1657: Use single formatted message for successfully callout message

### PR DESCRIPTION
**Pull request by Dmitriy-Litvinenko**
## Purpose
Use single formatted message for successfully callout message

## Refs
https://issues.folio.org/browse/UIU-1657

### CODE REVIEW

**Review by zburke — CHANGES_REQUESTED** [review]
Much better! `amount` just needs a little more clean up to make sure it's correctly handled as a numeric value. 

It's fine to just use `{amount, number}` here and leave the currency conversion to a later PR since it's outlined separately in [UIU-2026](https://issues.folio.org/browse/UIU-2026); OTOH, since it's only a tad more effort to handle this The Right Way you could just do it now.

**Comment by Dmitriy-Litvinenko** [comment]
@zburke Could you please rereview?

**Review by zburke — CHANGES_REQUESTED** [review]
Yay! Currency values formatted as currencies!!! Thank you!

But my petty complaint remains: use `of` instead of `Of` in `en.json`.

**Comment by Dmitriy-Litvinenko** [comment]
> Yay! Currency values formatted as currencies!!! Thank you!
> 
> But my petty complaint remains: use `of` instead of `Of` in `en.json`.

@zburke This part of original translation ""charge.messageOf": " fee/fine Of "," Could you please clarify can we keep it as is?

**Comment by zburke** [comment]
@Dmitriy-Litvinenko, yep, I understand the original translation contained "Of". It was always an error :)

**Comment by Dmitriy-Litvinenko** [comment]
@zburke  Thank you. Fixed. Could you please rereview?

**Review by zburke — APPROVED** [review]
LGTM!

**Pull request merged**
