### PR TITLE
UIU-1369: Assign permissions more efficiently

### PR DESCRIPTION
**Pull request by Baroquem**
https://issues.folio.org/browse/UIU-1369

This PR replaces the one-by-one permissions assignments with an all-in-one assignment, thanks to the API that Julian pointed out. For the case of assigning all available permissions to a user, that means a reduction from 200+ API requests down to one, or at most two. Hooray!

### CODE REVIEW

**Review by zburke — APPROVED** [review]
Nicely done! Thanks for the comments; they are helpful in general, and specifically in terms of helping to understand the not-really-obvious way that user permissions are managed. Thank you!

**Comment by zburke** [comment]
Aside, do we want to copy `eachPromise` to `stripes-connect` and export it there? It's a really useful piece of code, and I wonder if it could be the core of a generic client-side message-queue implementation that UI apps could use to hand of a batch of requests. Could we do something evil/clever with `eachPromise`, `dataKey`, and a callout-callback (e.g. [ClipCopy](https://github.com/folio-org/stripes-smart-components/blob/d0a0bef3dcd3115934ef25405d15c63dc7d46266/lib/ClipCopy/ClipCopy.js#L20-L29)) to create uniquely-named resources that would allow these requests to be processed asynchronously, in series, without worry that they could be stomped on by loading another page that accesses the same resource?

Thoughts @mkuklis, @skomorokh?

**Review by mkuklis — APPROVED** [review]
Nice work @Baroquem!

I agree with @zburke that it would be nice to be able to reuse it and I also agree with @skomorokh about `stripes-util`

**Comment by mkuklis** [comment]
I'm also glad that new api works!

**Comment by Baroquem** [comment]
Well, I can move that function to stripes-util as-is, if that's the consensus. Thanks for the feedback!

**Pull request merged**
