### PR TITLE
UIU-179

### PR DESCRIPTION
**Pull request by mbstacy**
UIU 179: Added Item Status formatter for Loan History(open,closed) and User Loan Details. If loan action is renewed, recalled, holdrequested, or recallrequested the Item Status reflects 'loan item status - loan action'

### CODE REVIEW

**Comment by MikeTaylor** [comment]
@mbstacy If you're happy with your own code, you should just go ahead and merge. If you would rather it be reviewed by someone else, by all means ask, but that is a service that you can take advantage of rather than a hoop you have to jump through.

**Comment by mbstacy** [comment]
@MikeTaylor I do not have permissions to merge into the repository. I'm happy with the code, but do not have a way to merge the code.

**Comment by mbstacy** [comment]
@MikeTaylor Thank you!

**Comment by MikeTaylor** [comment]
OK, @mbstacy, no problem. I've merged it for you.

I'm not clear yet on what our policies and procedures are in this area -- how one is supposed to apply for the right to merge code, and so on. We hope @funkymalc will clarify. In the mean time, feel free to ping me when you need code merged.

**Pull request merged**
